import { SearchPromotion, SelectPromotion, StandOutPromotion } from '../icons/index';

export const promotionData = [
  {
    label: 'Search',
    description:
      'Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.',
    icon: SearchPromotion,
  },
  {
    label: 'Select',
    description:
      'Choose from thousands of options generated by the slogan maker that fit your needs.',
    icon: SelectPromotion,
  },
  {
    label: 'Stand out',
    description: `Congrats on your new slogan. It's time to win the world!`,
    icon: StandOutPromotion,
  },
];

export const otherProductsData = [
  {
    label: 'Privacy Policy Generator',
    image: '/images/privacy-policy-generator.png',
    description:
      'Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.',
  },
  {
    label: 'Terms & Conditions Generator',
    image: '/images/t&c-generator.png',
    description:
      'Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.',
  },
  {
    label: 'Domain Name Generator',
    image: '/images/domain-name-generator.png',
    description:
      'Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.',
  },
  {
    label: 'Invoice Generator',
    image: 'images/invoice-generator.png',
    description:
      'Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.',
  },
];

export const footerLinks = [
  [
    {
      label: 'Contact',
    },
    {
      label: `FAQ's`,
    },
  ],
  [
    {
      label: 'Tutorials',
    },
    {
      label: `Blog`,
    },
  ],
  [
    {
      label: 'Privacy',
    },
    {
      label: `Banned items`,
    },
  ],
  [
    {
      label: 'About',
    },
    {
      label: `Jobs`,
    },
  ],
  [
    {
      label: 'Facebook',
    },
    {
      label: 'Twitter',
    },
    {
      label: 'Linkedin',
    },
  ],
];
