import { SearchPromotion, SelectPromotion, StandOutPromotion } from '../icons/index';

export const promotionData = [
  {
    label: 'Search',
    description:
      'Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.',
    icon: SearchPromotion,
  },
  {
    label: 'Select',
    description:
      'Choose from thousands of options generated by the slogan maker that fit your needs.',
    icon: SelectPromotion,
  },
  {
    label: 'Stand out',
    description: `Congrats on your new slogan. It's time to win the world!`,
    icon: StandOutPromotion,
  },
];
